apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-output
spec:
  steps:
    - name: check
      image: curlimages/curl:7.68.0
      script: |
        RESPONSE=$(curl -s http://localhost:3000)
        if [ "$RESPONSE" == "Hello Tech Meetup!" ]; then
          echo "Test passed!!"
        else
          echo "Test failed: expected 'Hello Tech Meetup!', got '$RESPONSE'"
          exit 1
        fi
