apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: check-node-app-output
spec:
  tasks:
    - name: install-dependencies
      taskRef:
        name: install-dependencies
    - name: start-server
      taskRef:
        name: start-server
      runAfter: 
        - install-dependencies
    - name: check-output
      taskRef:
        name: check-output
      runAfter: 
        - start-server

