apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-app-test-pipeline
spec:
  tasks:
    - name: start-server
      description: Start the Node.js server
      taskSpec:
        steps:
          - name: start
            image: your-repo/your-app:latest  
            script: |
              echo "Starting Node.js server..."
              node app.js &
              sleep 5  # Adjust the sleep duration if needed
    - name: check-output
      description: Check the output of the Node.js application
      runAfter:
        - start-server
      taskSpec:
        params:
          - name: EXPECTED_OUTPUT
          - value: $(params.EXPECTED_OUTPUT)
        steps:
          - name: check
            image: curlimages/curl:7.68.0
            script: |
              RESPONSE=$(curl -s http://localhost:3000)
              if [ "$RESPONSE" == "$(params.EXPECTED_OUTPUT)" ]; then
                echo "Test passed!"
              else
                echo "Test failed: expected '$(params.EXPECTED_OUTPUT)', got '$RESPONSE'"
                exit 1
              fi
