apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-server
spec:
  steps:
    - name: start
      image: node:16
      script: |
        node app.js &
        sleep 5
  workspaces:
    - name: source
